### PR TITLE
Feature/4: add guides for writting README.md and CONTRIBUTING.md files

### LINKED ISSUE #4: Write guide how to write READMEs and CONTRIBUTING guides in a separate site page

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
closes #4

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
@kbdharun, can u check it out via running site locally by `hugo server`? I am wondering what u think about such guides? BTW, how better to name "interaction guides"?

**Comment by kbdharun** [comment]
> @kbdharun, can u check it out via running site locally by `hugo server`? I am wondering what u think about such guides? BTW, how better to name "interaction guides"?

Sure

**Review by kbdharun — COMMENTED** [review]
image

Tested it, LGTM

**Comment by kbdharun** [comment]
Maybe you can change the site header/name from terminal to clip. Also, the GitHub page's URL seems to be long which is really bad for SEO. I would suggest having something smaller but we can't do anything about it as it uses the project name.

**Comment by EmilySeville7cfg** [comment]
> Maybe you can change the site header/name from terminal to clip.

I guess I can.

**Pull request merged**
